# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11-node
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - restore_cache:
          name: Restore Golang dependencies cache
          key: dependency-cache-{{ checksum "./server/glide.lock" }}
      - restore_cache:
          name: Restore NPM dependencies cache
          key: dependency-cache-{{ checksum "./webapp/package-lock.json" }}
      - type: shell
        name: 'Build artifacts'
        command: make dist
        environment:
            TERM: dumb
      - run:
          name: Test
          command: make test
      - save_cache:
          name: Save Golang dependencies cache
          key: dependency-cache-{{ checksum "./server/glide.lock" }}
          paths:
              - ./server/vendor
      - save_cache:
          name: Save NPM dependencies cache
          key: dependency-cache-{{ checksum "./webapp/package-lock.json" }}
          paths:
              - ./webapp/node_modules
      - store_artifacts:
          path: ./dist
          destination: build
